### ISSUE TITLE
11-directories_permissions may be wrong

### ISSUE THREAD

**Issue by HazemUsama** [Abdorithm/alx-system_engineering-devops#1]
Dear @Abdorithm 
`chmod -R +X .` changes directories and **files** and we should only change directories
try `chmod +x */` instead

XOXO

**Comment by HazemUsama** [comment]
It came to my attention that you might be not wrong.

i will search and tell you what i found ASAP.

**Comment by HazemUsama** [comment]
I understand you use `X` and it should only work with directories. but it acts like `x` when it comes to files and makes it executable anyway. I tried it myself.

This would be a valid answer
`chmod -R +X ./*/` same thing as `chmod -R +X */`

**Comment by Abdorithm** [comment]
![Screenshot from 2023-03-10 15-42-38](https://user-images.githubusercontent.com/87670345/224331643-e30b10fc-5f1e-4234-860f-87c790d543b2.png)
@HazemUsama 
Thanks for reaching out. The command works just fine. What I would say is to double check your resources. 
Tip: Searching and trying to find out a problem should be done before opening an issue.

**Comment by HazemUsama** [comment]
Thank you for letting me know that the command works fine and for your helpful tip on troubleshooting. I apologize for any confusion I may have caused earlier. I appreciate your expertise on this matter and I'm glad to have learned something new from you. Thanks again and have a great day!
